In [7]:
import torch

A= torch.rand(4,4)
A

tensor([[0.7126, 0.0898, 0.8904, 0.6171],
        [0.1064, 0.1930, 0.6698, 0.8147],
        [0.0673, 0.7855, 0.5438, 0.5021],
        [0.6127, 0.6719, 0.0070, 0.6346]])

In [8]:
B = torch.chunk(A, 2, 0)
B

(tensor([[0.7126, 0.0898, 0.8904, 0.6171],
         [0.1064, 0.1930, 0.6698, 0.8147]]),
 tensor([[0.0673, 0.7855, 0.5438, 0.5021],
         [0.6127, 0.6719, 0.0070, 0.6346]]))

In [9]:
C =  torch.chunk(A, 2, 1)
C

(tensor([[0.7126, 0.0898],
         [0.1064, 0.1930],
         [0.0673, 0.7855],
         [0.6127, 0.6719]]),
 tensor([[0.8904, 0.6171],
         [0.6698, 0.8147],
         [0.5438, 0.5021],
         [0.0070, 0.6346]]))

In [10]:
B=torch.split(A, 2, 0)
B

(tensor([[0.7126, 0.0898, 0.8904, 0.6171],
         [0.1064, 0.1930, 0.6698, 0.8147]]),
 tensor([[0.0673, 0.7855, 0.5438, 0.5021],
         [0.6127, 0.6719, 0.0070, 0.6346]]))