# 列表推导式与条件赋值

In [ ]:
L = []

def my_func(x):
    return 2*x

for i in range(5):
    L.append(my_func(i))

In [3]:
L

[0, 2, 4, 6, 8]

In [4]:
[my_func(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [7]:
[m+ "_" + n for m in ["a", "b"] for n in ["c", "d"]]

['a_c', 'a_d', 'b_c', 'b_d']

In [8]:
value = "cat" if 2 > 1 else "dog"

In [10]:
value

'cat'

In [14]:
L = [1,2,3,4,5,6,7]
[i if i <= 5 else 5  for i in L]

[1, 2, 3, 4, 5, 5, 5]

# 匿名函数与map方法

In [17]:
my_func = lambda x: 2*x
my_func(3)

6

In [20]:
multi_para_func = lambda x,y: x+y
multi_para_func(1,2)

3

In [23]:
[(lambda x:2*x)(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [25]:
list(map(lambda x,y: str(x)+"_"+y, range(5), list("abcde")))

['0_a', '1_b', '2_c', '3_d', '4_e']

# zip对象与enumerate方法

In [32]:
L1, L2, L3 = list('abc'), list('def'), list('hij')

In [33]:
list(zip(L1,L2,L3))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [35]:
tuple(zip(L1, L2, L3))

(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))

In [37]:
for i, j, k in zip(L1, L2, L3):
    print(i, j, k)

a d h
b e i
c f j


In [39]:
L = list("abcd")
for index, value in enumerate(L):
    print(index, value)

0 a
1 b
2 c
3 d


In [43]:
for index, value in zip(range(len(L)), L):
    print(index, value)

0 a
1 b
2 c
3 d


In [45]:
zipped = list(zip(L1,L2,L3))
zipped

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [48]:
list(zip(*zipped))

[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

# Numpy基础

In [51]:
import numpy as np

np.array([1,2,3])

array([1, 2, 3])

In [54]:
np.linspace(1,5,11) # 起始、终止（包含）、样本个数

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [56]:
np.arange(1,5,2) # 起始、终止（不包含）、步长

array([1, 3])

In [58]:
np.zeros((2,3)) # 传入元组表示各维度大小

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.eye(3) # 3*3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.eye(3, k=1) # 偏移主对角线1个单位的伪单位矩阵

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [65]:
np.full((2,3), 10) # 元组传入大小，10表示填充数值

array([[10, 10, 10],
       [10, 10, 10]])

In [66]:
np.full((2,3), [1,2,3]) # 每行填入相同的列表

array([[1, 2, 3],
       [1, 2, 3]])