## 数组创建

In [1]:
import numpy as np

a = np.array([2,3,4])
a

array([2, 3, 4])

In [2]:
a.dtype

dtype('int64')

In [3]:
b = np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [4]:
b = np.array([[1.5,2,3], [4,5,6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
b.dtype

dtype('float64')

In [6]:
c = np.array([[1,2],[3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [9]:
np.empty((2, 3)) 

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [11]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [12]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
from numpy import pi

x = np.linspace(0,2*pi,100)
f = np.sin(x) 

## 打印数组